# Generated by Django 3.2.7 on 2021-09-11 21:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_alter_workoutlog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 11, 21, 7, 32, 125526, tzinfo=utc)),
        ),
    ]
