# Generated by Django 3.2.7 on 2021-09-12 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_workoutlog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
